"""
backend/stylegan_engine/templates.py
Built-in templates that demonstrate model capabilities and push creative limits.
Each template is a named starting point with a description of what it produces.
"""

TEMPLATES = [
    {
        "id": "tpl_raw",
        "name": "Raw Output",
        "description": "No adjustments. Direct model output at default settings.",
        "model_hint": None,
        "params": {
            "seed": 0,
            "truncation_psi": 0.7,
            "noise_mode": "const",
            "mix_seed": None,
            "mix_layers": None,
            "layer_weights": None,
            "noise_strength": 1.0,
            "coarse_psi": None,
            "fine_psi": None,
        },
        "style_route": "none",
        "text_prompt": None,
    },
    {
        "id": "tpl_average_collapse",
        "name": "Average Collapse",
        "description": "Very low truncation pulls everything toward the model mean. Produces the most 'typical' face or object the model knows. Useful baseline.",
        "model_hint": None,
        "params": {
            "seed": 0,
            "truncation_psi": 0.2,
            "noise_mode": "const",
            "mix_seed": None,
            "mix_layers": None,
            "layer_weights": None,
            "noise_strength": 1.0,
            "coarse_psi": None,
            "fine_psi": None,
        },
        "style_route": "none",
        "text_prompt": None,
    },
    {
        "id": "tpl_full_chaos",
        "name": "Full Chaos",
        "description": "Maximum truncation. The model runs at full diversity — expect instability, structural breakdown, and the most alien outputs the network can produce.",
        "model_hint": None,
        "params": {
            "seed": 42,
            "truncation_psi": 1.4,
            "noise_mode": "random",
            "mix_seed": None,
            "mix_layers": None,
            "layer_weights": None,
            "noise_strength": 1.5,
            "coarse_psi": None,
            "fine_psi": None,
        },
        "style_route": "tv_wreckage",
        "text_prompt": None,
    },
    {
        "id": "tpl_structure_swap",
        "name": "Structure Swap",
        "description": "Two seeds with coarse layer mixing. Seed 0 provides surface detail, seed 1 provides pose and structure. A fundamental StyleGAN technique.",
        "model_hint": None,
        "params": {
            "seed": 0,
            "truncation_psi": 0.7,
            "noise_mode": "const",
            "mix_seed": 100,
            "mix_layers": [0, 1, 2, 3],
            "layer_weights": None,
            "noise_strength": 1.0,
            "coarse_psi": None,
            "fine_psi": None,
        },
        "style_route": "structure_transplant",
        "text_prompt": None,
    },
    {
        "id": "tpl_texture_donor",
        "name": "Texture Donor",
        "description": "Fine layer mixing — seed 1 donates only surface texture and color, seed 0 keeps all structural decisions. The two identities fuse at the skin level.",
        "model_hint": None,
        "params": {
            "seed": 0,
            "truncation_psi": 0.7,
            "noise_mode": "const",
            "mix_seed": 200,
            "mix_layers": [8, 9, 10, 11, 12, 13, 14],
            "layer_weights": None,
            "noise_strength": 1.0,
            "coarse_psi": None,
            "fine_psi": None,
        },
        "style_route": "fine_transplant",
        "text_prompt": None,
    },
    {
        "id": "tpl_split_psi",
        "name": "Split Truncation",
        "description": "Coarse and fine layers use different psi values. Coarse stays close to average (stable pose), fine runs wild (chaotic surface). Creates structured instability.",
        "model_hint": None,
        "params": {
            "seed": 7,
            "truncation_psi": 0.7,
            "noise_mode": "const",
            "mix_seed": None,
            "mix_layers": None,
            "layer_weights": None,
            "noise_strength": 1.0,
            "coarse_psi": 0.3,
            "fine_psi": 1.2,
        },
        "style_route": "none",
        "text_prompt": None,
    },
    {
        "id": "tpl_noise_flood",
        "name": "Noise Flood",
        "description": "High noise strength with random mode. The stochastic detail layer overwhelms the deterministic structure. Surface becomes primary.",
        "model_hint": None,
        "params": {
            "seed": 13,
            "truncation_psi": 0.8,
            "noise_mode": "random",
            "mix_seed": None,
            "mix_layers": None,
            "layer_weights": None,
            "noise_strength": 2.5,
            "coarse_psi": None,
            "fine_psi": None,
        },
        "style_route": "broken_chroma",
        "text_prompt": None,
    },
    {
        "id": "tpl_ghost",
        "name": "Ghost",
        "description": "High truncation + ghost contour route. Forms thin out to their outlines. Best on portrait models.",
        "model_hint": "face",
        "params": {
            "seed": 22,
            "truncation_psi": 0.9,
            "noise_mode": "random",
            "mix_seed": None,
            "mix_layers": None,
            "layer_weights": None,
            "noise_strength": 1.2,
            "coarse_psi": None,
            "fine_psi": None,
        },
        "style_route": "ghost_contour",
        "text_prompt": None,
    },
]
